The sentiment labels are:

    0 - negative
    1 - somewhat negative
    2 - neutral
    3 - somewhat positive
    4 - positive

In [1]:
train = pd.read_csv("../train.tsv", delimiter='\t', quoting=3)
train.tail()

PhraseId  SentenceId                     Phrase  Sentiment
156055    156056        8544                  Hearst 's          2
156056    156057        8544  forced avuncular chortles          1
156057    156058        8544         avuncular chortles          3
156058    156059        8544                  avuncular          2
156059    156060        8544                   chortles          2

In [2]:
test = pd.read_csv("../test.tsv", delimiter='\t', quoting=3)
test.tail()

PhraseId  SentenceId                                  Phrase
66287    222348       11855  A long-winded , predictable scenario .
66288    222349       11855    A long-winded , predictable scenario
66289    222350       11855                         A long-winded ,
66290    222351       11855                           A long-winded
66291    222352       11855                    predictable scenario

In [8]:
train.head()

PhraseId  SentenceId                                             Phrase  \
0         1           1  A series of escapades demonstrating the adage ...   
1         2           1  A series of escapades demonstrating the adage ...   
2         3           1                                           A series   
3         4           1                                                  A   
4         5           1                                             series   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2

In [24]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156060 entries, 0 to 156059
Data columns (total 4 columns):
PhraseId      156060 non-null int64
SentenceId    156060 non-null int64
Phrase        156060 non-null object
Sentiment     156060 non-null int64
dtypes: int64(3), object(1)
memory usage: 4.8+ MB


In [27]:
for i in train.columns:
    print(i,'(',train[i].nunique(),')','\n',train[i].unique())

PhraseId ( 156060 ) 
 [     1      2      3 ... 156058 156059 156060]
SentenceId ( 8529 ) 
 [   1    2    3 ... 8542 8543 8544]
Phrase ( 156060 ) 
 ['A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .'
 'A series of escapades demonstrating the adage that what is good for the goose'
 'A series' ... 'avuncular chortles' 'avuncular' 'chortles']
Sentiment ( 5 ) 
 [1 2 3 4 0]


In [20]:
train[train.SentenceId == 1][train.Sentiment == 1]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


PhraseId  SentenceId                                             Phrase  \
0          1           1  A series of escapades demonstrating the adage ...   
33        34           1  the gander , some of which occasionally amuses...   
47        48           1       but none of which amounts to much of a story   
49        50           1           none of which amounts to much of a story   

    Sentiment  
0           1  
33          1  
47          1  
49          1

In [21]:
train[train.Phrase == '.']

PhraseId  SentenceId Phrase  Sentiment
62        63           1      .          2

##### Issues
- 각 SentenceId의 첫 Phrase가 full sentences이고 나머진 일부분들....
- 한 글자만으로 이루어진 Phrase가 있어서 stopword를 쓰면 안된다고 판단.
- .조차도 버리면 안되는건가...

In [150]:
from KaggleWord2VecUtility import KaggleWord2VecUtility

In [151]:
sentences = []
for phrase in train['Phrase']:
    sentences += KaggleWord2VecUtility.review_to_sentences(phrase, remove_stopwords=False)

C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:219: UserWarning: "b'...'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:219: UserWarning: "b'...'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:219: UserWarning:

In [153]:
len(sentences)

156448

In [154]:
import logging
logging.basicConfig(
    format='%(asctime)s : %(levelname)s : $(massage)s',
    level=logging.INFO
)

In [155]:
from gensim.models import word2vec

In [156]:
num_features = 40
min_count = 20
num_worker = 4
window = 10
downsampling = 1e-3
sg = 0
model = word2vec.Word2Vec(sentences, workers=num_worker, size=num_features,
                          min_count = min_count, window=window,
                          sample=downsampling, sg=sg)

2018-08-15 22:58:31,643 : INFO : $(massage)s
2018-08-15 22:58:31,644 : INFO : $(massage)s
2018-08-15 22:58:31,660 : INFO : $(massage)s
2018-08-15 22:58:31,679 : INFO : $(massage)s
2018-08-15 22:58:31,698 : INFO : $(massage)s
2018-08-15 22:58:31,719 : INFO : $(massage)s
2018-08-15 22:58:31,737 : INFO : $(massage)s
2018-08-15 22:58:31,757 : INFO : $(massage)s
2018-08-15 22:58:31,774 : INFO : $(massage)s
2018-08-15 22:58:31,793 : INFO : $(massage)s
2018-08-15 22:58:31,813 : INFO : $(massage)s
2018-08-15 22:58:31,831 : INFO : $(massage)s
2018-08-15 22:58:31,849 : INFO : $(massage)s
2018-08-15 22:58:31,866 : INFO : $(massage)s
2018-08-15 22:58:31,884 : INFO : $(massage)s
2018-08-15 22:58:31,901 : INFO : $(massage)s
2018-08-15 22:58:31,920 : INFO : $(massage)s
2018-08-15 22:58:31,931 : INFO : $(massage)s
2018-08-15 22:58:31,932 : INFO : $(massage)s
2018-08-15 22:58:31,950 : INFO : $(massage)s
2018-08-15 22:58:31,951 : INFO : $(massage)s
2018-08-15 22:58:31,970 : INFO : $(massage)s
2018-08-15

In [157]:
model.init_sims(replace=True)

2018-08-15 22:58:35,020 : INFO : $(massage)s


In [158]:
model.doesnt_match("man woman child kitchen".split())

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `doesnt_match` (Method will be removed in 4.0.0, use self.wv.doesnt_match() instead).
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\gensim\matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int32 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


'kitchen'

In [159]:
model.most_similar("horror")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\gensim\matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int32 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('monster', 0.7339290380477905),
 ('crass', 0.6766730546951294),
 ('worst', 0.6576613783836365),
 ('season', 0.6498938798904419),
 ('equival', 0.6281961798667908),
 ('buff', 0.6273522973060608),
 ('holiday', 0.6243687868118286),
 ('b', 0.6079187393188477),
 ('phoni', 0.6073557138442993),
 ('crime', 0.599737286567688)]

In [160]:
def makeFeatureVec(words, model, num_features):
    """
    주어진 문장에서 단어 벡터의 평균을 구하는 함수(임베딩벡터의 평균)
    """
    # 속도를 위해 0으로 채운 배열로 초기화 한다.
    featureVec = np.zeros((num_features,),dtype="float32")

    nwords = 0.
    # Index2word는 모델의 사전에 있는 단어명을 담은 리스트이다.
    # 속도를 위해 set 형태로 초기화 한다.
    index2word_set = set(model.wv.index2word)
    # 루프를 돌며 모델 사전에 포함이 되는 단어라면 피처에 추가한다.
    for word in words:
        if word in index2word_set:
            nwords = nwords + 1.
            featureVec = np.add(featureVec,model[word])
    # 결과를 단어수로 나누어 평균을 구한다.
    featureVec = np.divide(featureVec,nwords)
    return featureVec

In [161]:
def getAvgFeatureVecs(reviews, model, num_features):
    # 리뷰 단어 목록의 각각에 대한 평균 feature 벡터를 계산하고 
    # 2D numpy 배열을 반환한다.
    
    # 카운터를 초기화 한다.
    counter = 0.
    # 속도를 위해 2D 넘파이 배열을 미리 할당한다.
    reviewFeatureVecs = np.zeros(
        (len(reviews),num_features),dtype="float32")
    
    for review in reviews:
       # 매 1000개 리뷰마다 상태를 출력
       if counter%1000. == 0.:
           print("Review %d of %d" % (counter, len(reviews)))
       # 평균 피처 벡터를 만들기 위해 위에서 정의한 함수를 호출한다.
    # 해당 row의 review의 토큰들의 임베딩벡터숫자를 평균낸다.(즉, review별로 임베딩벡터의 평균을 내는 것.)
       reviewFeatureVecs[int(counter)] = makeFeatureVec(review, model, \
           num_features)
       # 카운터를 증가시킨다.
       counter = counter + 1.
    return reviewFeatureVecs

In [162]:
# 멀티스레드로 4개의 워커를 사용해 처리한다.
def getCleanReviews(reviews):
    clean_reviews = []
    clean_reviews = KaggleWord2VecUtility.apply_by_multiprocessing(\
        reviews["Phrase"], KaggleWord2VecUtility.review_to_wordlist,\
        workers=4)
    return clean_reviews

In [163]:
trainDataVecstrainDat  = getAvgFeatureVecs(\
    getCleanReviews(train), model, num_features)

Review 0 of 156060
Review 1000 of 156060
Review 2000 of 156060


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  app.launch_new_instance()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in true_divide


Review 3000 of 156060
Review 4000 of 156060
Review 5000 of 156060
Review 6000 of 156060
Review 7000 of 156060
Review 8000 of 156060
Review 9000 of 156060
Review 10000 of 156060
Review 11000 of 156060
Review 12000 of 156060
Review 13000 of 156060
Review 14000 of 156060
Review 15000 of 156060
Review 16000 of 156060
Review 17000 of 156060
Review 18000 of 156060
Review 19000 of 156060
Review 20000 of 156060
Review 21000 of 156060
Review 22000 of 156060
Review 23000 of 156060
Review 24000 of 156060
Review 25000 of 156060
Review 26000 of 156060
Review 27000 of 156060
Review 28000 of 156060
Review 29000 of 156060
Review 30000 of 156060
Review 31000 of 156060
Review 32000 of 156060
Review 33000 of 156060
Review 34000 of 156060
Review 35000 of 156060
Review 36000 of 156060
Review 37000 of 156060
Review 38000 of 156060
Review 39000 of 156060
Review 40000 of 156060
Review 41000 of 156060
Review 42000 of 156060
Review 43000 of 156060
Review 44000 of 156060
Review 45000 of 156060
Review 46000 of 15

In [164]:
testDataVecs = getAvgFeatureVecs(\
        getCleanReviews(test), model, num_features )

Review 0 of 66292
Review 1000 of 66292
Review 2000 of 66292
Review 3000 of 66292
Review 4000 of 66292
Review 5000 of 66292
Review 6000 of 66292
Review 7000 of 66292
Review 8000 of 66292
Review 9000 of 66292


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  app.launch_new_instance()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in true_divide


Review 10000 of 66292
Review 11000 of 66292
Review 12000 of 66292
Review 13000 of 66292
Review 14000 of 66292
Review 15000 of 66292
Review 16000 of 66292
Review 17000 of 66292
Review 18000 of 66292
Review 19000 of 66292
Review 20000 of 66292
Review 21000 of 66292
Review 22000 of 66292
Review 23000 of 66292
Review 24000 of 66292
Review 25000 of 66292
Review 26000 of 66292
Review 27000 of 66292
Review 28000 of 66292
Review 29000 of 66292
Review 30000 of 66292
Review 31000 of 66292
Review 32000 of 66292
Review 33000 of 66292
Review 34000 of 66292
Review 35000 of 66292
Review 36000 of 66292
Review 37000 of 66292
Review 38000 of 66292
Review 39000 of 66292
Review 40000 of 66292
Review 41000 of 66292
Review 42000 of 66292
Review 43000 of 66292
Review 44000 of 66292
Review 45000 of 66292
Review 46000 of 66292
Review 47000 of 66292
Review 48000 of 66292
Review 49000 of 66292
Review 50000 of 66292
Review 51000 of 66292
Review 52000 of 66292
Review 53000 of 66292
Review 54000 of 66292
Review 550

In [165]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [167]:
forest = RandomForestClassifier(n_estimators=100, random_state=2018).fit(trainDataVecstrainDat, train['Sentiment'])

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [169]:
model.wv.index2word

['the',
 'a',
 'of',
 'and',
 'to',
 'it',
 's',
 'in',
 'is',
 'that',
 'as',
 'film',
 'with',
 'movi',
 'for',
 'an',
 'be',
 'this',
 'but',
 'on',
 'you',
 't',
 'n',
 'by',
 'one',
 'more',
 'his',
 'about',
 'not',
 'like',
 'at',
 'or',
 'than',
 'from',
 'all',
 'have',
 'are',
 'has',
 'make',
 'charact',
 'so',
 'stori',
 'out',
 'time',
 'up',
 'rrb',
 'most',
 'who',
 'good',
 'too',
 'into',
 'lrb',
 'work',
 'comedi',
 'if',
 'what',
 'their',
 'no',
 'much',
 'i',
 'can',
 'your',
 'way',
 'just',
 'life',
 'some',
 'even',
 'feel',
 'perform',
 'doe',
 'will',
 'love',
 'well',
 'look',
 'littl',
 'funni',
 'do',
 'veri',
 'director',
 'been',
 'ani',
 'bad',
 'get',
 'onli',
 'come',
 'which',
 'year',
 'he',
 'other',
 'new',
 'there',
 'see',
 'enough',
 'her',
 'was',
 'own',
 'action',
 'us',
 'they',
 'watch',
 'thing',
 'made',
 'old',
 'audienc',
 'entertain',
 'take',
 'end',
 'plot',
 'two',
 'someth',
 'interest',
 'minut',
 'act',
 'would',
 'go',
 'emot',


In [ ]:
score = np.mean(cross_val_score(forest, trainDataVecstrainDat, train['Sentiment'], cv=5, scoring='roc_auc'))
score